### ISSUE TITLE
как запустить бота

### ISSUE THREAD

**Issue by a1sbes** [bomzheg/aiogram_template#4]

**Comment by bomzheg** [comment]
Попробую на память с телефона. Если не получится - отпишитесь, пожалуйста, откорректируем

Требуется запущенный Postgresql и установленный python 3.10

* Скопировать шаблон конфига 
```bash
cp -r config_dist config
```
* Заполнить config/config.yml своими значениями
* Создать и активировать venv
```bash
python -m venv venv
source venv/bin/activate
```
* Установить зависимости
```bash
pip install -r requirements.txt
```
* Заполнить alembic.ini (скорее всего только url базы данных)
* Применить миграции 
```bash
alembic upgrade head
```
* Запустить 
```bash
python -m app
```

**Comment by a1sbes** [comment]
ошибка в pip instal нужно pip install, бро хотел спросить, а зачем venv?

**Comment by bomzheg** [comment]
> ошибка в pip instal нужно pip install

Спасибо, поправил

> а зачем venv?

Чтобы не засорять глобальный site-packages пакетами конкретного проекта. По сути venv единственный способ избегать конфликта зависимостей между несколькими проектами

**Comment by a1sbes** [comment]
а ещё вопрос: я не пользовался postgres его можно установить и настроить на vps сервере линукс(дебиан или убунту) ?

**Comment by bomzheg** [comment]
> а ещё вопрос: я не пользовался postgres его можно установить и настроить на vps сервере линукс(дебиан или убунту) ?

Это выходит уже слишком далеко за рамки данного темплейта

Могу посоветовать поискать подходящий чат в https://t.me/it_chats и спросить там

**Comment by bomzheg** [comment]
добавил описание запуска в README
